# Numpy
- numpy = numarical python
- It helps us to do the math with big lists esay and faster.
- Also known as the hart of datascience.
- statistics, machine learning, and data analysis.

In [19]:
import numpy as np
np.__version__

'2.3.4'

In [20]:
l = [1, 2, 3, 4]

# convert list to array

In [21]:
a = np.array(l)
a

array([1, 2, 3, 4])

In [22]:
type(a)

numpy.ndarray

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [25]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

# creating a zeros

In [27]:
np.zeros(10) # by default it will gives the float values

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros(10, dtype = int) # hyper-parameter tuening

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [31]:
np.zeros((2, 2, 2), dtype = int)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [33]:
np.ones((2, 2, 2), dtype = int)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

- - - 

In [34]:
np.random.rand(5)
# np = package
# random = module
# rand = function

array([0.87804075, 0.34145398, 0.51252034, 0.94946611, 0.37413369])

In [35]:
np.random.rand(3, 4)

array([[0.51447546, 0.82611445, 0.61472386, 0.45171995],
       [0.93991479, 0.49682088, 0.72590933, 0.00632506],
       [0.84048413, 0.83628713, 0.59905865, 0.84576702]])

In [36]:
np.random.randint(5)

4

In [37]:
np.random.randint(1, 9, 5)

array([4, 1, 8, 3, 2], dtype=int32)

In [38]:
np.random.randint(1, 9, (5, 5))

array([[8, 4, 2, 6, 4],
       [5, 5, 5, 8, 6],
       [1, 5, 4, 2, 4],
       [1, 4, 3, 1, 6],
       [4, 5, 7, 5, 5]], dtype=int32)

# change the shape of an array

In [39]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# slicing array

In [43]:
a = np.random.randint(1, 9, 25).reshape(5, 5)
a

array([[5, 5, 1, 3, 8],
       [7, 8, 1, 6, 7],
       [7, 2, 2, 6, 1],
       [3, 5, 5, 7, 1],
       [7, 4, 6, 4, 2]], dtype=int32)

In [44]:
a[:]

array([[5, 5, 1, 3, 8],
       [7, 8, 1, 6, 7],
       [7, 2, 2, 6, 1],
       [3, 5, 5, 7, 1],
       [7, 4, 6, 4, 2]], dtype=int32)

In [45]:
a[1]

array([7, 8, 1, 6, 7], dtype=int32)

In [46]:
a[-3]

array([7, 2, 2, 6, 1], dtype=int32)

In [47]:
a[2:5]

array([[7, 2, 2, 6, 1],
       [3, 5, 5, 7, 1],
       [7, 4, 6, 4, 2]], dtype=int32)

In [48]:
a[1, 4]

np.int32(7)

In [49]:
a[-5:2]

array([[5, 5, 1, 3, 8],
       [7, 8, 1, 6, 7]], dtype=int32)

In [50]:
b = np.random.randint(1, 9, (5, 5))
b

array([[1, 6, 7, 6, 5],
       [4, 4, 4, 7, 4],
       [3, 4, 1, 4, 5],
       [5, 1, 8, 8, 4],
       [3, 5, 3, 6, 2]], dtype=int32)

In [51]:
b[-1]

array([3, 5, 3, 6, 2], dtype=int32)

In [52]:
b[::-1]

array([[3, 5, 3, 6, 2],
       [5, 1, 8, 8, 4],
       [3, 4, 1, 4, 5],
       [4, 4, 4, 7, 4],
       [1, 6, 7, 6, 5]], dtype=int32)

In [53]:
b[:, 2]

array([7, 4, 1, 8, 3], dtype=int32)

In [55]:
b[1:, 2:4]

array([[4, 7],
       [1, 4],
       [8, 8],
       [3, 6]], dtype=int32)

In [57]:
b[1:3, 3:5]

array([[7, 4],
       [4, 5]], dtype=int32)

# indexing

In [58]:
b

array([[1, 6, 7, 6, 5],
       [4, 4, 4, 7, 4],
       [3, 4, 1, 4, 5],
       [5, 1, 8, 8, 4],
       [3, 5, 3, 6, 2]], dtype=int32)

In [60]:
b[3, 4]

np.int32(4)

In [61]:
b[b> 5]

array([6, 7, 6, 7, 8, 8, 6], dtype=int32)

In [63]:
a = np.arange(0, 25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
a[a> 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [68]:
c = [[1, 2], [3, 4], [5, 6]]
c = np.ravel(c)
c

array([1, 2, 3, 4, 5, 6])

In [70]:
np.transpose(a)

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [71]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.vstack([a, b])
print(c)

[[1 2]
 [3 4]]


In [72]:
d = np.hstack([a, b])
d

array([1, 2, 3, 4])

- - -

In [2]:
import numpy as np
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
a3 = np.hstack([a1, a2])
a3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [3]:
arr = np.arange(1, 11)
arr[(arr > 3) & (arr<8)]

array([4, 5, 6, 7])

In [4]:
b = np.array([[1, 1], [2, 2]])
print(b.sum(axis = 0))
print(b.sum(axis = 1))

[3 3]
[2 4]
